project:
  type: book
  output-dir: docs

book:
  title: "learningDiary"
  author: "Xiaoyi Chens"
  date: "2024/1/18"
  chapters:
    - index.qmd
    - intro.qmd
    - wk2_Portfolio.Rmd
    - wk5_GEE.qmd
    - wk7_classification1.qmd
    - wk9_SAR_data.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    darkmode: true
  pdf:
    documentclass: scrreprt

editor: visual

